fire_event:
  description: fires a event
  fields:
    event_type:
      description: Name of the event to be sent
      example: "state_changed"
    data:
      description: Data to send as event payload
      example: 
        var: 'val'